### PR TITLE
proxy support(jruby style)

### PR DESCRIPTION
**Pull request by toshi-miura**
please S3 proxy supoort.

### CODE REVIEW

**Comment by muga** [comment]
Interesting. I think that it's better to configure http proxy within `in:` config like following. Why do you choose JRuby style proxy setting? Can you tell me your use case?

**Comment by toshi-miura** [comment]
I think 's a embulk design where proxy is settins.
this is my memo.

---------------------------------------------------------------------------------

 proxy setting is system setting on java std library (-D option)
 proxy setting is config setting on aws java library and apache common 
 proxy setting is system setting on powershell(win. .net)
 proxy setting is system setting on embulk plugin install (env https_proxy(jruby style ) )
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 where is proxy setting on embulk plugin ? (Not only s3 plugin )

I think as follows.

When a plugin is codding in jruby, proxy setting (jruby style) is Active.
When a plugin is codding in java std library, proxy setting (-D option) is Active.
When a plugin is codding in aws java library, proxy setting  is codding matter.

---------------------------------------------------------------------------------

this is bad.I need guidance..

**Comment by frsyuki** [comment]
* having proxy setting is good
* but it should be passed using ConfigSource. If you want to use environment variable, you can use liquid template engine to embed environment variables in config file.
* coding style is broken.

**Comment by toshi-miura** [comment]
thank you

**Pull request closed without merging**
