### PR TITLE
add skip_glacier_object option to avoid loading a object stored at glacier

### PR DESCRIPTION
**Pull request by ujun**
A getObject method throws an AmazonS3Exception when a target S3 path contains a object whose storage class is "Glacier". 

This PR handles above Exception.

```
try {
    GetObjectRequest request = new GetObjectRequest(bucket, iterator.next());
    S3Object obj = client.getObject(request);
    return new ResumableInputStream(obj.getObjectContent(), new S3InputStreamReopener(client, request, obj.getObjectMetadata().getContentLength()));
} catch (AmazonS3Exception ex) {
    return null;
}

```

### CODE REVIEW

**Comment by sakama** [comment]
Thanks for your PR.

I think there are 2 use cases for Gracier users.
* Skip Gracier stored files as you implemented
* Don't skip these files and throw Exception as current implementation is doing

For example, some Embulk plugins(Especially parser and filter plugins) has `stop_on_invalid` option.
`stop_on_invalid: true` : Plugin will stop and throw Exception if invalid data comes.
`stop_on_invalid: false` : Plugin will output warn logs and skip invalid row. But don't stop processing.
https://github.com/embulk/embulk/blob/v0.8.39/embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java#L100
https://github.com/embulk/embulk/blob/v0.8.39/embulk-standards/src/main/java/org/embulk/standards/CsvParserPlugin.java#L389


Additionally, I don't think it's good to skip all `AmazonS3Exception`.
Only skip limited cases is better.

@muga What do you think about?

**Comment by sakama** [comment]
@ujun I talked with other maintainers.
Could you consider above points?

**Comment by muga** [comment]
@ujun @sakama thank you for sending the PR. can you share the full stacktrace that you got first? we think that `AmazonS3Exception` is not proper grain for handling this issue. We'd better to handle it by fine-grain like an exception message, error code or something.

**Comment by ujun** [comment]
@sakama @muga 
Thank you so much for reviewing. 

As you mentioned, I also think the way of this PR is not suitable.
I have experienced following error message when execute `embulk guess` command which accesses a glacier object.

```
********************************** INFORMATION **********************************
  Join us! Embulk-announce mailing list is up for IMPORTANT annoucement such as
    compatibility-breaking changes and key feature updates.
  https://groups.google.com/forum/#!forum/embulk-announce
*********************************************************************************

2017-12-15 22:48:34.006 +0900 [INFO] (0001:guess): Loaded plugin embulk-input-s3 (0.2.11)
2017-12-15 22:48:35.395 +0900 [INFO] (0001:guess): Try to read 32,768 bytes from input source
com.amazonaws.services.s3.model.AmazonS3Exception: The operation is not valid for the object's storage class (Service: Amazon S3; Status Code: 403; Error Code: InvalidObjectState; Request ID: C7FCB5327CF87D18), S3 Extended Request ID: CwBUbi1KcSW23ceQ/tyYZ7LtBI/TdbIDsTl30uTry+Z1GraDVxklDURiDNP01V0NF9RXNfKkKqA=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1239)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:823)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:506)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3595)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1116)
        at org.embulk.input.s3.AbstractS3FileInputPlugin$SingleFileProvider.openNext(AbstractS3FileInputPlugin.java:357)
        at org.embulk.spi.util.InputStreamFileInput.nextFile(InputStreamFileInput.java:167)
        at org.embulk.exec.SamplingParserPlugin.readSample(SamplingParserPlugin.java:194)
        at org.embulk.exec.SamplingParserPlugin.readSample(SamplingParserPlugin.java:189)
        at org.embulk.exec.SamplingParserPlugin.run(SamplingParserPlugin.java:178)
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:156)
        at org.embulk.exec.SamplingParserPlugin$1.run(SamplingParserPlugin.java:61)
        at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:126)
        at org.embulk.exec.SamplingParserPlugin.transaction(SamplingParserPlugin.java:170)
        at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:120)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:77)
        at org.embulk.spi.util.Decoders.transaction(Decoders.java:33)
        at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:117)
        at org.embulk.input.s3.AbstractS3FileInputPlugin.resume(AbstractS3FileInputPlugin.java:115)
        at org.embulk.input.s3.AbstractS3FileInputPlugin.transaction(AbstractS3FileInputPlugin.java:102)
        at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:67)
        at org.embulk.exec.SamplingParserPlugin.runFileInputSampling(SamplingParserPlugin.java:51)
        at org.embulk.spi.FileInputRunner.guess(FileInputRunner.java:88)
        at org.embulk.exec.GuessExecutor.doGuess(GuessExecutor.java:119)
        at org.embulk.exec.GuessExecutor.access$000(GuessExecutor.java:36)
        at org.embulk.exec.GuessExecutor$1.run(GuessExecutor.java:96)
        at org.embulk.exec.GuessExecutor$1.run(GuessExecutor.java:92)
        at org.embulk.spi.Exec.doWith(Exec.java:25)
        at org.embulk.exec.GuessExecutor.guess(GuessExecutor.java:92)
        at org.embulk.EmbulkEmbed.guess(EmbulkEmbed.java:158)
        at org.embulk.EmbulkRunner.guessInternal(EmbulkRunner.java:228)
        at org.embulk.EmbulkRunner.guess(EmbulkRunner.java:66)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:462)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:100)
        at org.embulk.cli.Main.main(Main.java:28)

Error: The operation is not valid for the object's storage class (Service: Amazon S3; Status Code: 403; Error Code: InvalidObjectState; Request ID: C7FCB5327CF87D18)
```

Regards,

**Comment by sakama** [comment]
Thanks.

My suggestion is define `skip_gracier_data` or something option.
And implementation example is as following.

I implemented [embulk-output-dynamodb](https://github.com/sakama/embulk-output-dynamodb/blob/master/src/main/java/org/embulk/output/dynamodb/DynamodbUtils.java#L63) before and DynamoDB sometimes returns `AmazonServiceException`.
`AmazonS3Exception` is a subclass of `AmazonServiceException` and I think it will return similar response.
ref. [AmazonS3Exception (AWS SDK for Java - 1.11.247)](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/AmazonS3Exception.html)

```java
try {
    ...
} catch (AmazonS3Exception ex) {
    int statusCode = ex.getStatusCode(); // I've not checked this code works or not
    if (statusCode == 403) {
        if (task.getSkipGracierData()) {
            log.warn("Skipped \"{}\" that stored at Gracier. status code: {}", "/path/to/file.txt", statusCode);
        }
        else {
            throw new ConfigException(ex);
        }
    }
}

**Comment by ujun** [comment]
@sakama @muga 

Sorry for late reply. 
I have modified the code to handle exceptions more finely based on @sakama 's implementaton. 
Please review again 🙏

**Comment by sakama** [comment]
Thanks for fixing.

1. It may better to contain user friendly message when throw `ConfigException` since default exception message "The operation is not valid for the object's storage class (Service: Amazon S3; Status Code: 403;" is difficult to understand.

```java
String message = "";
throw ConfigException(message, ex);
```

2. Write unit test is better
But it should need to use Mock and with some difficulties.
Please let me know at that time.

Everything else looks good to me.

**Comment by muga** [comment]
What do you think about the usage of the following storage class of S3 files to handle this? I'm not sure but, the plugin might be able to skip "Glacier" storage class files when it lists S3 file during transaction phase. So, it doesn't need to submit unnecessary GET request for the "Glacier" files on each input task, anyway.
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/StorageClass.html

**Comment by sakama** [comment]
I roughly checked at AWS S3 and IDCF Cloud RiakCS(has S3 compatible API).
Following code seems to work and should be better.
```java
for (S3ObjectSummary s : ol.getObjectSummaries()) {
    if (s.getStorageClass().equals(StorageClass.Glacier.toString())) {
        if (skipGracierObject) {
            log.warn("message");
        }
        else {
            throw new ConfigException("message");
        }
    }
    ...
}
```

**Comment by ujun** [comment]
Thanks, I'm going to try it.

@sakama 
> Write unit test is better
Well,,, I'm new at writing a test with mock in Java, and therefore will spend large amount of time if I do that.  😭

**Comment by sakama** [comment]
@ujun Sorry to be late.
I wrote unit test for your PR.
Could you review this?
https://github.com/ujun/embulk-input-s3/pull/1

**Comment by ujun** [comment]
@sakama 

I'm sorry I'm late. Thank you for your help.
I will check from now.

**Comment by ujun** [comment]
@sakama 
Thank you for PR. 
I have merged.

**Comment by ujun** [comment]
@sakama 

I realized that there is no reference to this new option on README. Should I add ?

**Comment by sakama** [comment]
@ujun Yeah. It is helpful.
And I talked with @muga and `skip_glacier_objects` is better since target objects are multiple.
I'm going to merge after your update.

**Comment by ujun** [comment]
@sakama 

> skip_glacier_objects is better since target objects are multiple.

Thanks. I have done and modified README.md
19c0d93

**Comment by sakama** [comment]
Merged. Thanks for taking long time.
I will release soon #66

**Comment by sakama** [comment]
Released as v0.2.14

**Pull request merged**
