### PR TITLE
proxySupport (confVersion)

### PR DESCRIPTION
**Pull request by toshi-miura**
proxySupport (confVersion)

### CODE REVIEW

**Comment by muga** [comment]
I'm so sorry, I was missing this ticket. I will move forward this.

**Comment by muga** [comment]
This feature is necessary. I think that it's good to introduce `HttpProxy` class to represent http proxy as one of config units. The config unit has several attributes: "use_ssl", "host", "port", "username", and "password" and users can specify them. I also think that `HttpProxy` can be initialized by several well-known environment variables "HTTP_PROXY", "HTTPS_PROXY", "http_proxy", "https_proxy" if config unit are not defined in the Embulk config. I will prototype it on another ticket.

**Comment by hito4t** [comment]
👍

**Comment by muga** [comment]
I merged https://github.com/embulk/embulk-input-s3/pull/48 and close this ticket. Please let me know if you have any questions.

**Pull request closed without merging**
